### ISSUE TITLE
No images downloaded

### ISSUE THREAD

**Issue by Hugo-Matias** [Xonshiz/comic-dl#210] opened 2019-01-31 22:09 UTC
I was downloading the first ongoing of Deadpool from Readcomiconline.to and at about 20 issues from completion the program started to download 0 images, the cbz is still created but is empty. I must say that the CloudFlare trick seems to be working as it keeps going through the issues without stoping, it just refuses to download the images. This problem started at around 3 hours ago and it still persists, is there some kind of ip softban that i triggered? It happens site wide with other series as well. 

Edit: I use Tachiyomi on android and the readcomiconline extension also started to give me errors stating "Page list is empty", they most likely changed something on their website

Edit2: It's downloading fine again, i guess they softban ips for some hours. Sorry to bother you with this.

**Comment by tak19** [comment] 2019-02-17 21:21
I am having similar problem with readcomiconline.to . It's fooling cloudflare but then downloading 0 images. 

It's been 4 days. Did they change something on the website?



**Screenshot:** https://imgur.com/a/yg3NOzB

**Comment by Rogerooo** [comment] 2019-02-17 21:34
I was able to download some issues a couple of days back but it soon started to behave like this and gives me an empty file. Im now using comicextra for the odd issues im not able to find on getcomics. If i really need something from readcomiconline i'll just show all pics and download them with a plugin like Image Downloader, filter the url for blogspot and you'll have the pages.

**Comment by Hafler** [comment] 2019-04-09 02:03
I am having a very similar issue even after rebuilding in docker. The docker approach works fine on my laptop, but I was downloading using a server hosted in another country. Using the docker container on my server results in the same symptoms. Unfortunately, the other sites don't seem to have quite as large of a selection as readcomiconline.to.

```
docker run -it --rm -v $(pwd):/directory -w /directory comic-dl:py3.6.5-stretch comic_dl -dd /directory --convert cbz --keep false --verbose -i https://readcomiconline.to/Comic/Die/Issue-1\?id\=145164

***Starting the script in Verbose Mode***

Fooling CloudFlare...Please Wait...
[Comic-dl] Done : Die [Issue - 1] : : 0image(s) [00:00, ?image(s)/s]
CBZ File : /directory/Die/Die - Ch Issue - 1
Deleted the files...
Total Time Taken To Complete : 11.056415796279907
```

**Comment by Xonshiz** [comment] 2019-07-01 10:48
I'll look into this issue.

**Comment by MarissaBlackwing** [comment] 2019-07-05 15:51
Same issue here of zero images being downloaded after previously working fine, though for me it's been over seven hours and it still doesn't seem to be working anymore.

**Comment by DjexVruly** [comment] 2019-07-23 17:07
I had the same problem on readcomiconline.to and was able to solve by changing my ip address on my vpn.

**Comment by Xonshiz** [comment] 2019-10-22 08:02
See folks, the issue is that RCO puts a temp ban on IPs if you start hitting them like that. I would suggest that you wait a while for downloading things from RCO. I can't promise that I can provide with a proper fix for this, but I've been trying to get something going for this scenario. This problem has been there for too long. This issue wasn't there when I was using the PhantomJS in the original project.... But, it had other complications and issues of its own. Not using Selenium and PhantomJS was a very hard choice I had to make and this particular issue was a trade off for that.

**Closed** 2021-09-04 18:30 UTC
