### ISSUE TITLE
Unable to download entire series from readcomiconline.to with -i command

### ISSUE THREAD

**Issue by CaptainJawZ** [Xonshiz/comic-dl#169] opened 2018-09-12 22:38 UTC
So this is a weird bug, when I try to download an entire series using -i it only downloads the newest episode (or first if I use --sorting. But it wont download any other issues. 

However if I add the link using -c and then -a it works perfectly downloading the entire series, but then it just makes my database bigger and harder to maintain. 

**Command You Gave**: comic_dl -i https://readcomiconline.to/Comic/Champions-2016
**Expected Behaviour** : download all available issues from the series
**Actual Behaviour** : only downloast the lastest (or first if using --sort) but will prompt error when trying to download the next issue

<script src="https://gist.github.com/CaptainJawZ/de79ccd854aa23568af6a0b15f81e440.js"></script>

![image](https://user-images.githubusercontent.com/43111068/45456993-9bda2980-b6b2-11e8-9dc5-26202ddf377e.png)

**Comment by thehyperborean** [comment] 2018-09-14 14:39
Same issue here.

**Comment by darodi** [comment] 2018-09-14 19:54
duplicate of #163 , #155, #158, #145, #132

fixed in #149

wait for the new binaries.
In the meantime, you could get the pre-release given in #163

**Comment by thehyperborean** [comment] 2018-09-18 17:09
Brilliant, used #163, works a charm, thank you so much!

**Comment by Xonshiz** [comment] 2018-09-29 11:50
Checked on my end and latest binaries don't have this issue.
Same Issues : #163 , #165 , #169

**Closed by Xonshiz** 2018-09-29 11:50 UTC
