### ISSUE TITLE
[Comic-dl] Auto processing with error for readcomiconline.to Detected the new Cloudflare challenge.                                                                               

### ISSUE THREAD

**Issue by jloffredo** [Xonshiz/comic-dl#271] opened 2020-06-26 15:51 UTC
Getting that error more and more. 

[Comic-dl] Auto processing with error for https://readcomiconline.to/Comic/[comicurl] : Detected the new Cloudflare challenge.

**Comment by magnuschase293** [comment] 2020-07-04 01:47
Same

**Comment by vengeance101** [comment] 2020-07-04 18:55
After digging a bit, I assume this is why I'm getting a 503. cloudscraper seems to be shut down (at least, no repo anymore). I manually ran cloudscraper against readcomiconline and it wouldn't bypass (always returned cloudfare page).

I think this project is just broken until someone can bypass the anti-scrapers again.

**Comment by magnuschase293** [comment] 2020-07-04 20:20
I've been looking into the matter myself and thought a possibility may be to use cfscrape instead of cloudscraper (didn't tried It). Also I found out you can simply fully load the comic and save the webpage which downloads all the .jpgs inside a folder.

**Comment by vengeance101** [comment] 2020-07-05 05:15
I think selenium would work pretty well here as well, but I'm sure another cloudfare workaround will come out soon.

**Comment by magnuschase293** [comment] 2020-07-05 14:41
Thanks, I will try to use Selenium, but I need to learn the module from scratch. 
 Do you know if it can manage the ChromeDevTools protocol??? It's for another project.

**Comment by vengeance101** [comment] 2020-07-05 15:50
Yes, fairly certain it can. I haven't used it much either but if it provides a workaround to this I might just make a small little script.

**Comment by magnuschase293** [comment] 2020-07-15 22:59
I actually made the script if you are interested here's the [repo](https://github.com/magnuschase293/comic_getter)

**Comment by Peepijeep** [comment] 2020-07-28 11:08
Hello,
I dont know how to use that script. Can youb build a windows-binary, so I can use it? I really want to download the comics from comic.dl.

**Comment by Xonshiz** [comment] 2021-09-04 18:15
I was using selenium initially for readcomingonline website, but selenium is heavy and slow. I think the issue is fixed now that we switch the CF challenge library. I'm closing this for now, please feel free to re-open if the issue is still there in the latest binary.

Don't forget to run the script with the verbose flag and share the generated error log as well.

**Closed by Xonshiz** 2021-09-04 18:15 UTC
