### ISSUE TITLE
Only downloading the last issue in readcomiconline.to

### ISSUE THREAD

**Issue by LINKAD0** [Xonshiz/comic-dl#155] opened 2018-07-13 02:25 UTC
Command I Gave : 'comic_dl.exe -i "https://readcomiconline.to/Comic/Marvel-Knights-Spider-Man-2004" -v' 
Expected Behaviour : I expected to download all the issues/chapters
Actual Behaviour : Only the last one was downloaded
My Logs are available [HERE](https://gist.github.com/LINKAD0/2bfd31959c5302168ca58af04a8960db)

**Comment by darodi** [comment] 2018-07-13 17:10
works in the pull request #149 

duplicate of #145 #132

**Comment by LINKAD0** [comment] 2018-07-13 19:14
For use this fix i need to use the python script right? Well i cant make it work , i write the same thing (but with .py not .exe) but it simply doesnt do anything 
![image](https://user-images.githubusercontent.com/15948573/42709570-5815c3ba-86b7-11e8-98c3-654e59103ca6.png)
even with the "-v" command it doest create a error_log file

**Comment by LINKAD0** [comment] 2018-07-13 19:35
It worked, thanks for the help!

**Closed** 2018-07-27 11:45 UTC
