### ISSUE TITLE
Cannot download from readcomicsonline?

### ISSUE THREAD

**Issue by TenEye** [Xonshiz/comic-dl#158] opened 2018-07-19 14:19 UTC
I get the following error when I try and run the script. It will download the first comic in the series and then give this error:

Traceback (most recent call last):
  File "comic_dl\__main__.py", line 10, in <module>
    ComicDL(sys.argv[1:])
  File "comic_dl\comic_dl.py", line 226, in __init__
    user_input = args.input[0]
  File "comic_dl\honcho.py", line 100, in checker
    return 0
  File "comic_dl\sites\readcomicOnlineto.py", line 28, in __init__
    conversion=conversion, delete_files=delete_files)
  File "comic_dl\sites\readcomicOnlineto.py", line 141, in full_series
    elif str(sorting).lower() in ['old', 'asc', 'ascending', 'oldest', 'a']:
IndexError: list index out of range
[7380] Failed to execute script __main__

**Comment by darodi** [comment] 2018-07-20 20:00
works in the pull request #149
https://github.com/darodi/comic-dl/tree/fix_mangarock_autodl

duplicate of #145 #132 #155

**Comment by TenEye** [comment] 2018-07-20 20:35
Still get the same error :(

**Comment by TenEye** [comment] 2018-07-20 20:37
FYI: I'm using the Windows Binary, not Python. It was working fine and then all of a sudden half way through downloading a comic it started playing it and now just refuses to do anything other than the first comic in a series.

**Comment by darodi** [comment] 2018-07-20 21:42
i made the exe binary here 
https://github.com/darodi/comic-dl/releases/download/2018.07.20-fix/comic-dl.exe

**Comment by TenEye** [comment] 2018-07-20 22:14
Thank you so much for your time and help. It worked! :D

**Closed** 2018-07-27 11:45 UTC
